### ISSUE TITLE
/sbin/shutdown missing

### ISSUE THREAD

**Issue by mike632t** [FooDeas/raspberrypi-ua-netinst#121]
Assume deliberatly omitted..?

**Comment by FooDeas** [comment]
"ls /sbin/shutdown"?

**Comment by mike632t** [comment]
Not there...

[2.0.0_ls.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1592440/2.0.0_ls.txt)

**Comment by FooDeas** [comment]
There should be a symlink to /bin/systemctl from package "systemd-sysv"...
Please attach `/var/log/raspberrypi-ua-netinst.log`.

**Comment by mike632t** [comment]
Had to redo the install to produce logs, selecting to delete them after the install was a bad idea, but I now know that whatever the problem is it is reproducable!  

[2.0.0_ls.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1593182/2.0.0_ls.txt)
 [2.0.1-installer-config.txt](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1593176/2.0.1-installer-config.txt)
[2.0.1-raspberrypi-ua-netinst.log ](https://github.com/FooDeas/raspberrypi-ua-netinst/files/1593177/2.0.1-raspberrypi-ua-netinst.log)

**Comment by FooDeas** [comment]
Thanks a lot!
The `systemd-sysv` package is part of the server preset only. That was forgotten in the docs because I didn't distinguish between the init systems. You can add it to the packages in the installer-config if you need it.

I'll revise the docs according this.

**Comment by mike632t** [comment]
Awsome installer - very happy running stretch on my original Pi B.  The install doesn't take too long and stretch it boots suprisingly quickly too.

Many thanks for your efforts.  Happy New year!

**Comment by SlySven** [comment]
Only recently discovered this project but as I am a staunch SysV `init` die-hard who avoids letting the `systemd` hydra anywhere near the PID 1 spot - I just wanted to advise that I recently managed to force a `systemd` less install with a:
```
preset="minimal"
packages="sysvinit-core,sysvinit-utils,sysv-rc,vim-tiny,iputils-ping,wget,ca-certificates,rsyslog,cron,dialog,locales,tzdata,less,man-db,logrotate,bash-completion,console-setup,apt-utils,libraspberrypi-bin,raspi-copies-and-fills,vim,aptitude"
```
I.e. use do everything else from the `preset="server"` case but avoiding supping from *that* bottle of cool-aide.

I've run into problems with the no shutdown, no reboot situation on, I think it was a Linux laptop - IIRC there was a `poweroff` command that did work though.  I suspect it was probably induced in a Debian Wheezy to Stretch `dist-upgrade` which got messed up part way through or got confused because by default that version change (from {Deb|Raspb}ian 8.x to 9.x) tries to switch you from systemV `init` to `systemd`  unless you are really, *really, **firm*** about not letting it...
