### ISSUE TITLE
Add support for 64-bit

### ISSUE THREAD

**Issue by davralin** [FooDeas/raspberrypi-ua-netinst#195]
https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370

Would be swelll if I could use ua-netinst to bootstrap 64-bit-images.

I realize that this will probably take a while though...

**Comment by kpfleming** [comment]
I'm working on this right now (doing some final testing before posting an issue for discussion, since the changes are extensive). One thing to note: I'm doing this by adding support for Debian as a base (both for the installer and the installed system), I'm not doing any work to try to install 64-bit Raspbian or Raspberry Pi OS (as I prefer to just use plain Debian).

**Comment by Rocco83** [comment]
Any news? Or even, how to test it out?

**Comment by ovimano** [comment]
Hello!
Can I test this pull request?

**Comment by davralin** [comment]
For antoine still looking for something, this might be a viable solution:

https://raspi.debian.net/
