### ISSUE TITLE
Modules missing on reinstall

### ISSUE THREAD

**Issue by Jodes81** [FooDeas/raspberrypi-ua-netinst#31]
Following the `README`, I wanted to reinstall, with a few modifications. 

I made some modifications to the files in `/boot/`, eg adding "bring-your-own" files to `my-files.list` and `/boot/config/files`.

Then I run:

```
mv /boot/config-reinstall.txt /boot/config.txt
reboot
```

During the  installation, I get this:

```
Waiting for serial device... OK

Searching for boot device...
SD card detected.
Boot files found on SD card.

==================================================
raspberrypi-ua-netinst
==================================================
Revision v1.3.0 (6e71081)
Built on Wed Sep 14 23:34:00 CEST 2016
Running on Raspberry Pi version B
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
Starting HWRNG succeeded!
Copying boot files... OK
==================================================
=== Start executing installer-config.txt. ========
=== Finished executing installer-config.txt. =====
==================================================

Network configuration:
  ip_addr = dhcp
  wlan_ssid = <...>
  wlan_psk = <...>
  online_config =

depmod: can't change directory to 'lib/modules/4.4.21+': No such file or directory
Loading additional drivers.
  Loading driver 'brcmfmac'... modprobe: can't change directory to '4.4.21+': No such file or directory

Oh noes, something went wrong!
You have 10 seconds to hit ENTER to get a shell...
```

I noticed that the files in `/boot/`, such as the `bcm*.dtb`, `kernel.img` and `start*.elf` files are different to those in the original installer files. Might this be the problem? 

I've also tried it without modifying anything (except `mv /boot/config-reinstall.txt /boot/config.txt`) but it does the same thing.

So far I've had success by changing the files in /boot/: 
- Restore bcm2708-rpi-b.dtb
- Restore bcm2708-rpi-b-plus.dtb
- Restore bcm2708-rpi-cm.dtb
- Restore bcm2709-rpi-2-b.dtb
- Restore bcm2710-rpi-3-b.dtb
- Delete bcm2710-rpi-cm3.dtb
- Restore kernel.img

Then it re-installs successfully. (I know the last file was necessary, but I'm not sure about the others.)

**Comment by FooDeas** [comment]
Kernel v4.4.21+ on raspberrypi-ua-netinst v1.3.0? There is the problem because v1.3.0 came with 4.4.13+ (stored in installer.cpio.gz)...

If you do a reinstall, you should update to the new version. Have a look at the new available variables for installer-config.txt. There are some very useful regarding localization and keyboard layout...

Backup your installer-config.txt and other changes you made from /boot. Then delete all files and folders there, replace them with the current raspberrypi-ua-netinst and apply your customization. I think this will fix it for you.
Please report! (If you still have problems, post your installer-config.txt.)

**Comment by FooDeas** [comment]
I see the problem: Reinstallation fails because the **kernel** (kernel.img/kernel7.img) has been updated by the running system. The installer loads it on reinstall boot and misses the modules in initramfs.

To fix it, read my suggestion above. (But replacing the kernel.img and kernel7.img from the original used installer does the trick, too.)
Thanks for reporting!

**Comment by Jodes81** [comment]
You're welcome, thanks for sorting it! Excellent tool.
