### ISSUE TITLE
Add notice about release variable in build script

### ISSUE THREAD

**Issue by thijstriemstra** [FooDeas/raspberrypi-ua-netinst#99]
"release is set to "stretch" by default" is mentioned in the changelog but as far as i can see, `jessie` is no longer supported. So this should probably be mentioned explicitly in the changelog.

**Comment by FooDeas** [comment]
I hope we didn't break anything with stretch. Jessie and wheezy _should_ still work...

**Comment by thijstriemstra** [comment]
I saw some commits that *should* have broken it, let me find them.

@FooDeas or are you **not** talking about building, because I don't see how the references updated here (libssl 1.0.2 for example) https://github.com/FooDeas/raspberrypi-ua-netinst/commit/2c1b8747f5aa9e8d612c3731eca32e7bbf65b1d5 are compatible with jessie.

**Comment by FooDeas** [comment]
You're right. I don't think, building is still possible with jessie. But I see no reason why we need this.
The installer itself can install all three releases! It tried this one week ago without any problems.

**Comment by thijstriemstra** [comment]
Ok I fully agree @FooDeas, but let's make a note of that (in a positive way ;)) in the release notes/changelog: `if you want to use an older version of raspbian, you'll need an older version of this program if you want to build the installer from scratch`

**Comment by FooDeas** [comment]
But that's wrong. If you want to use an older version of raspbian. Just set the release version in the installer-config.
The build.sh content can and should be left as it is.

**Comment by thijstriemstra** [comment]
Fair enough.

**Comment by FooDeas** [comment]
I thought about it again.
The problem is: The build environment has to be always up to date with the highest release that is intended to be installed.
When I see the package dependency changes with the update to stretch and the workload, I come to the decision that the whole build process has to be rewritten. This will resolve many similar problems permanently.

Before then, the release version in the build process can't be changed - unfortunately this has always been the case.
